language: node_js

node_js:
  - "6"

addons:
  code_climate:
    repo_token: 99b7cd218cb787be006fcdffddc28a85a210592bd92c657caf2b7c9a3ae5b2da

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info